version: "3.8"

services:
  # Backend API
  nextest-backend:
    image: node:18-alpine
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache git python3 make g++ &&
        git clone https://github.com/murillobc/tutoriais-nxt.git . &&
        npm ci &&
        npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist &&
        echo '🚀 Backend buildado com sucesso! Iniciando servidor...' &&
        node dist/index.js
      "
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:cQM6q7g505tP@postgres_tuto_nxt_postgres:5432/postgres
      - SESSION_SECRET=${SESSION_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - WEBHOOK_URL=${WEBHOOK_URL}
    restart: always
    networks:
      - network_public
    volumes:
      - nextest_backend_logs:/app/logs
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.nextest-api.rule=Host(`api.automai.com.br`)
        - traefik.http.routers.nextest-api.entrypoints=websecure
        - traefik.http.routers.nextest-api.tls.certresolver=letsencryptresolver
        - traefik.http.services.nextest-api.loadbalancer.server.port=3000
        - traefik.http.middlewares.nextest-cors.headers.accesscontrolalloworiginlist=*
        - traefik.http.middlewares.nextest-cors.headers.accesscontrolallowheaders=*
        - traefik.http.middlewares.nextest-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS
        - traefik.http.routers.nextest-api.middlewares=nextest-cors

  # Redis para cache
  nextest-redis:
    image: redis:7-alpine
    restart: always
    networks:
      - network_public
    volumes:
      - nextest_redis_data:/data

volumes:
  nextest_backend_logs:
  nextest_redis_data:

networks:
  network_public:
    external: true
    name: network_public
