version: "3.8"

services:
  nextest-backend:
    build:
      context: https://github.com/murillobc/tutoriais-nxt.git
      dockerfile_inline: |
        FROM node:18-alpine
        WORKDIR /app
        RUN apk add --no-cache python3 make g++
        COPY . .
        RUN npm ci
        RUN npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
        EXPOSE 3000
        CMD ["node", "dist/index.js"]
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:cQM6q7g505tP@postgres_tuto_nxt_postgres:5432/postgres
      - SESSION_SECRET=${SESSION_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - WEBHOOK_URL=${WEBHOOK_URL}
    restart: always
    networks:
      - network_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.nextest-api.rule=Host(`api.automai.com.br`)
        - traefik.http.routers.nextest-api.entrypoints=websecure
        - traefik.http.routers.nextest-api.tls.certresolver=letsencryptresolver
        - traefik.http.services.nextest-api.loadbalancer.server.port=3000

networks:
  network_public:
    external: true
    name: network_public
