version: '3.8'

services:
  # Aplicação principal
  nextest-app:
    image: nextest-tutorials:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:cQM6q7g505tP@postgres_tuto_nxt_postgres:5432/postgres
      - SESSION_SECRET
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - SMTP_FROM
      - WEBHOOK_URL
    ports:
      - "3000:3000"
    volumes:
      - nextest-logs:/app/logs
    networks:
      - nextest-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Redis para cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nextest-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  redis_data:
  nextest-logs:

networks:
  nextest-network:
    driver: overlay
